model:
  visual:
    model: "resnet"
    train_baseline: false
    finetune: true
    embedding_dim: 512
  text:
    model: "bert"
    train_baseline: false
    max_len: 100
    num_layers: 2
    embedding_dim: 768
    dropout: 0.25
  region:
    model: "grounding_dino1" # "grounding_dino1", "grounding_dino2", "grounding_dino3", "grounding_dino4", "grounding_dino5"
    num_regions: 2
    embedding_dim: 256
  without_alignment: false
  without_gating: false
  cross_modal_baseline: false
  context_baseline: false
  hidden_dim1: 512
  hidden_dim2: 512
  embedding_dim: 512
  dropout: 0.25
  _lambda: 0.2
  num_attns: 4
  num_classes: 3

training:
  batch_size_mvsa_single: 64
  batch_size_mvsa_multiple: 128
  batch_size_climate_tv: 64
  epochs: 10
  optimizer: "adam_w" # "adam", "adam_w"
  lr: 0.001
  weight_decay: 0.0001
  lr_decay_factor: 0.1
  lr_decay_step_size: 3
  grad_clip: 1.0
  use_class_weight: false
  gamma: 0.0