model:
  vnet: "resnet"
  tnet: "bert"
  rnet: "fasterrcnn_bua"
  vbase: false
  tbase: false
  cross_modal_only: false
  linear_combination: false
  max_len: 128
  rf_dim: 2048
  d_dim: 512
  k_dim: 64
  lambda: 0.2
  scale_exponent: 0.0
  num_classes: 3
  num_regions: 2 
  temperature:
    schedule_t: false
    t: 1.0
    start_t: 2.0
    end_t: 1.0
    total_iters: 3

training:
  batch_size_mvsa_single: 64
  batch_size_mvsa_multiple: 128
  epochs: 10
  lr: 0.001
  weight_decay: 0.00001
  lr_decay_factor: 0.1
  lr_decay_step_size: 10